services:
    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        hostname: kafka-ui
        container_name: kafka-ui
        ports:
            - "8080:8080"
        environment:
            DYNAMIC_CONFIG_ENABLED: true
        networks:
            - thesis-network
networks:
    thesis-network:
        external: true
