services:
    postgres:
        container_name: postgres_container
        image: quay.io/debezium/example-postgres:2.1
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        command: |
            postgres 
            -c wal_level=logical
            -c hot_standby=on 
            -c max_wal_senders=10 
            -c max_replication_slots=10 
            -c hot_standby_feedback=on
        ports:
            - "5432:5432"
        networks:
            - thesis-network
volumes:
    postgres:
networks:
    thesis-network:
        external: true
