services:
    redis:
        image: redis:6.0.7
        container_name: redis
        restart: always
        volumes:
            - redis_volume_data:/data
        ports:
            - 6379:6379
        networks:
            - thesis-network

volumes:
    redis_volume_data:
networks:
    thesis-network:
        external: true
